---
# This is the base execution for running against parmstrong.ca
# systems and includes the appropriate certificates

version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest"

ansible_config: "./ansible.cfg"

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  append:
    - ADD ca.crt /etc/pki/ca-trust/source/anchors/
    - RUN update-ca-trust extract
