---
# This file uses version 3 schema supporting AAP 2.4 on RHEL9

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest"

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_galaxy:
    # ENV ANSIBLE_GALAXY_SERVER_LIST ensures the recognition other ENV vars
    # for the ALL CAPS names of the servers in the list, see below
    #    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub,private_hub
    # need to ensure private hub certificate for use with private hub
    # see prepend_base
    # ARG below must be exported in the shell of the user executing the build command
    # and passed as --build-arg for the ansible-builder build command
    # e.g. ansible-builder build --build-arg ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_LIST=galaxy_base,private_hub,automation_hub
    - ENV ANSIBLE_GALAXY_SERVER_GALAXY_BASE_URL=https://galaxy.ansible.com/
    # RH automation hub
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://cloud.redhat.com/api/automation-hub/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
    # Private hub
    - ENV ANSIBLE_GALAXY_SERVER_PRIVATE_HUB_URL=https://aaphub24.parmstrong.ca/api/galaxy/
    - ARG ANSIBLE_GALAXY_SERVER_PRIVATE_HUB_TOKEN

  # adding the ca crt from IdM here allows it to be used
  # later in the build process
  prepend_base:
    - ADD ca.crt /etc/pki/ca-trust/source/anchors/
    - RUN update-ca-trust extract
