---
collections:
  - name: "community.general"
  - name: "community.mysql"
  - name: "ansible.netcommon"
  - name: "ansible.posix"
  - name: "ansible.utils"
  - name: "ansible.controller"
  - name: "redhat.rhel_idm"
  - name: "redhat.satellite"
  - name: "redhat.satellite_operations"
  - name: "redhat.rhel_system_roles"
  - name: "azure.azcollection"
  - name: "vmware.vmware"
  - name: "infra.ah_configuration"
  - name: "infra.leapp"
  - name: "infra.lvm_snapshots"
  - name: "infra.convert2rhel"
  - name: "infra.eda_configuration"
  - name: "infra.ee_utilities"
  - name: "infra.osbuild"
