---
collections:
  - name: community.general
  - name: "community.mysql"
  - name: "ansible.netcommon"
  - name: "ansible.posix"
  - name: "ansible.utils"
  - name: "ansible.controller"
  - name: "redhat.rhel_idm"
  - name: "redhat.satellite"
  - name: "redhat.satellite_operations"
  - name: "redhat.rhel_system_roles"
  - name: "azure.azcollection"
  - name: "community.vmware"
